### PR TITLE
Add support for string ids (guids)

### PR DESCRIPTION
**Pull request by Jimver**

### CODE REVIEW

**Review by Archer6621 — CHANGES_REQUESTED** [review]
Hey, this looks like a good suggestion, but the method signatures (e.g. for adding stock to an item) still have `int` in them for the indices, could you also change these as well? :)

**Comment by Jimver** [comment]
> 
> 
> Hey, this looks like a good suggestion, but the method signatures (e.g. for adding stock to an item) still have `int` in them for the indices, could you also change these as well? :)

The values in those methods need to remain `int` right? Because they are used as an index to the `item_ids` list so they shouldn't be changed to `str` I think.

**Review by kPsarakis — APPROVED** [review]
Tested the changes and they work for both integer and string guids

**Comment by Archer6621** [comment]
> 
> 
> > Hey, this looks like a good suggestion, but the method signatures (e.g. for adding stock to an item) still have `int` in them for the indices, could you also change these as well? :)
> 
> The values in those methods need to remain `int` right? Because they are used as an index to the `item_ids` list so they shouldn't be changed to `str` I think.

Ah correct! I guess the naming we used confused me a bit there :) It used to be that there were no lists as well in an earlier iteration, but we had added them back since.

**Pull request merged**
